### ISSUE TITLE
cannot find avd in system path

### ISSUE THREAD

**Issue by gameboxthing** [thedrhax-dockerfiles/android-avd#6]
fails to run. Produces the following error:
PANIC: cannot find AVD system path. Please define ANDROID_SDK_ROOT

**Comment by TheDrHax** [comment]
I updated this image to the latest version of `thedrhax/android-sdk` in f3ba19976ca10890e30e8f9fef2ed3251854acb6. It should work now :+1:

**Comment by gameboxthing** [comment]
perfect. Works great!! will this be pushed to the docker hub?

**Comment by TheDrHax** [comment]
Tag `26` has been already updated. I forgot to push the same image to the `latest`. It is now up to date too!

**Comment by gameboxthing** [comment]
sweet as, thanks.
